### ISSUE TITLE
Setting up PyTorch plugin "bias_act_plugin"... Failed!

### ISSUE THREAD

**Issue by ms-ufad** [VinAIResearch/QC-StyleGAN#2]
在cu11.1 torch 1.9.0上运行，报错如下：
Setting up PyTorch plugin "bias_act_plugin"... Failed!
/QCstylegan/torch_utils/ops/bias_act.py:121: UserWarning: Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:
Traceback (most recent call last):
  File "/QCstylegan/torch_utils/ops/bias_act.py", line 116, in _init
    extra_cuda_cflags=["--use_fast_math"],
  File "/QCstylegan/torch_utils/custom_ops.py", line 126, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, verbose=verbose_build, sources=sources, **build_kwargs)
  File "/usr/local/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1092, in load
    keep_intermediates=keep_intermediates)
  File "/usr/local/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1303, in _jit_compile
    is_standalone=is_standalone)
  File "/usr/local/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1379, in _write_ninja_file_and_build_library
    check_compiler_abi_compatibility(compiler)
  File "/usr/local/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 283, in check_compiler_abi_compatibility
    if not check_compiler_ok_for_platform(compiler):
  File "/usr/local/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 243, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
  File "/usr/local/conda/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/conda/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/conda/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/conda/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'which': 'which'

  + traceback.format_exc()
Setting up PyTorch plugin "upfirdn2d_plugin"... Failed!
/QCstylegan/torch_utils/ops/upfirdn2d.py:42: UserWarning: Failed to build CUDA kernels for upfirdn2d. Falling back to slow reference implementation. Details:

**Comment by v-datnvt2** [comment]
Tks for your question!
You should use PyTorch 1.7.1 .
